### ISSUE TITLE
More meaningful name for sliedes files

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#12]
Slides images are called slide1, slide2 etc. As I told - try avoiding naming files, variables, functions, classes this way - give them meaningfull names.

**Comment by AgnieszkaKurek** [comment]
var file = "<img src=\"../images/slides/slide" + number +".jpg\"/>"  ;
thereby such naming slides  function changeslide is easy to manufacture.
I have to change the name, to write function code was more difficult - It does not make sense
Especially the images Galleria are arranged in a random, and their name is not significant.

**Comment by AgnieszkaKurek** [comment]
function changeslide()
        {
            number++; if (number > 5) number = 1;

```
        var file = "<img src=\"../images/slides/slide" + number +".jpg\"/>"  ;

        document.getElementById("slider").innerHTML = file;
        $("#slider").fadeIn(500);
        timer1=setTimeout("changeslide()", 5000);
        timer2=setTimeout("hide()", 4500);
    }
```

**Comment by Krzysiek102** [comment]
Makes sense. Ok. Lets leave it as it is
