### ISSUE TITLE
X-UA-Compatible meta in html files

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#17]
In html files you have something like this is declared:
```html
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrom1" />
```
Do you have some special content that requires using this header? If no, please remove it.

**Comment by AgnieszkaKurek** [comment]
<meta http-equiv="X-UA-Compatible" content="IE=edge">  makes the page can be opened in Internet Explorer. So this is useful declared

**Comment by Krzysiek102** [comment]
Ok, so lets leave it.
