### ISSUE TITLE
Cleanup gitignore file

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#2]
.gitignore file contains a lot of rubbish that are not needed. 
Please make a revision what is the purpose of this file and  clean it up - leave only content that has the impact.

**Comment by AgnieszkaKurek** [comment]
I removed the redundant information contained in the file .gitignore. For now, the file remains empty.

**Comment by Krzysiek102** [comment]
I do not see these any changes in this file. Are you sure that you pushed the changes?

**Comment by AgnieszkaKurek** [comment]
now it should be OK

**Comment by Krzysiek102** [comment]
Now it is ok. I will close the issue.
