### ISSUE TITLE
start using table header tags

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#3]
your table defined in battle.html does not use table header tag:
http://www.w3schools.com/tags/tag_th.asp
Please start using it defining headers.

**Comment by AgnieszkaKurek** [comment]
Done

**Comment by Krzysiek102** [comment]
Please join appropriate commit that fixes it with this issue.

**Comment by AgnieszkaKurek** [comment]
[https://github.com/AgnieszkaKurek/WordWarI/commit/f2b0e732b5aafaec5760ab9fc088970834a6499e](url)

**Comment by Krzysiek102** [comment]
What is the link pasted above? 
When I click it, it redirects me to page https://github.com/AgnieszkaKurek/WordWarI/issues/url where I have information 404 page not found.

**Comment by AgnieszkaKurek** [comment]
f2b0e732b5aafaec5760ab9fc088970834a6499e

**Comment by Krzysiek102** [comment]
Ok. Now there is a reference to commit that solves it, but commit itself does not have a reference to the issue. Please add issue number to the commit comment.
Next time in order to link a commit with an issue, please add in a commit title number of issue preceded with #, for example #3 will create a reference to issue nr 3.
