### ISSUE TITLE
refresh property in html file

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#4]
What is the purpose of this refresh property:
https://github.com/AgnieszkaKurek/WordWarI/blob/master/battle.html#L6
https://github.com/AgnieszkaKurek/WordWarI/blob/master/index.html#L6
https://github.com/AgnieszkaKurek/WordWarI/blob/master/persons.html#L6
?
If it is not intended, please remove it.

**Comment by AgnieszkaKurek** [comment]
removed

**Comment by Krzysiek102** [comment]
Please join appropriate commit that fixes it with this issue.
