### ISSUE TITLE
Apply directory separation of different types of files

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#5]
In order to preserve the clarity of the solution, it would be good to put css file (files) into separate directory, the same as javaScript and html files. Please use recently modified repo as an example.

**Comment by AgnieszkaKurek** [comment]
done

**Comment by Krzysiek102** [comment]
Please join appropriate commit that fixes it with this issue.

**Comment by Krzysiek102** [comment]
As I can see you've separated html and images into dedicated directories. Please do the same with css styles, regardless of their current numbers.
