### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#54]
It should be WorldWarI or WorldWat1 intead of WordWarI

**Comment by Krzysiek102** [comment]
I do not know why you linked this commit to this change.
Also you did not change readme file - it still contains information about WordWarI.
Please check all usages of Word in your files and fix them all.

**Comment by AgnieszkaKurek** [comment]
You do not read with understanding:
1. Please unling this commit: 
https://github.com/AgnieszkaKurek/WorldWarI/commit/820c14866aa143bda9822f9c1f971baedaf6b4f2
from this issue
2. You still did not change all usages of word phrase - please have a look at bower.json file> I wrote "Please check all usages of Word in your files and fix them all."

**Comment by Krzysiek102** [comment]
Please also change description in github.

**Comment by Krzysiek102** [comment]
Commit 
https://github.com/AgnieszkaKurek/WorldWarI/commit/820c14866aa143bda9822f9c1f971baedaf6b4f2
is still connected
