### ISSUE TITLE
Do not declare elements with non unique ids

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#6]
In battle.html you use the same id for several different elements, for example:
https://github.com/AgnieszkaKurek/WordWarI/blob/master/battle.html#L159
https://github.com/AgnieszkaKurek/WordWarI/blob/master/battle.html#L167
id should be unique across the whole application.
Probably you want to use class, not id instead. 
Please remind yourself what is the difference between id and class in html and css.
Change also css style to refer to these elements appropriatelly.

**Comment by AgnieszkaKurek** [comment]
I used to class

**Comment by Krzysiek102** [comment]
Please join appropriate commit that fixes it with this issue.
"I used to class" - what does it mean?

**Comment by AgnieszkaKurek** [comment]
5bf95e413ce4e5b2a170accf92bcc40dd184833d

**Comment by AgnieszkaKurek** [comment]
f94a59d45e0dde1b16ee87af86a3f6ce92b39d90

**Comment by Krzysiek102** [comment]
Ok. Now there is a reference to commit that solves it, but commit itself does not have a reference to the issue. Please add issue number to the commit comment.

**Comment by Krzysiek102** [comment]
As for the code it looks ok - ids are not used for referencing html elements in styles.

**Comment by Krzysiek102** [comment]
Looks ok
