### ISSUE TITLE
Add instruction how to run the project

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#9]
There is no instruction how to run the project. It would be good to add information about it in readme file

**Comment by AgnieszkaKurek** [comment]
I thought that, readme file  is being created when the project is finished.

**Comment by Krzysiek102** [comment]
Instruction should be avaiable from the beggining and systematically updated.

**Comment by Krzysiek102** [comment]
"Website was created using languages: html, CSS, and frameworks: jquery ()."
- jquery is written as jquery, not as jquery ()
- jquery is not a framework - it is library
- html and css are not typical languages, so it is uncommont to write html language or css language. If we want to call html as a language, usually we call it as a markup language.
- you did not mention javaScript here

To sum it up, it would be better to write:
Website was created using html, css, javaScript and jquery.

**Comment by Krzysiek102** [comment]
install node http server: npm install -g http-server
Is it required? Why

**Comment by Krzysiek102** [comment]
While triggering bower install there is an error in a console:
'bower invalid-meta
The "name is recommended to be lowercase, can contain digits, dots, dashes
'
